UPDATE `creature_ai_texts` SET `content_loc2` = 'Le %s gémit, mais semble autrement non affecté par la rouille' WHERE `entry` = -174;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Empereur Thaurissan ne veut pas être dérangé ! Retournez en arrière maintenant ou faites face à votre mort,  faibles mortels !' WHERE `entry` = -1194;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Préparez-vous à être Maudit!' WHERE `entry` = -1195;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous venez juste d\'être MAUDIT' WHERE `entry` = -1196;
UPDATE `creature_ai_texts` SET `content_loc2` = 'TIMMY !' WHERE `entry` = -1197;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dites-moi ... dites-moi tout!' WHERE `entry` = -1198;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Secrets coquins' WHERE `entry` = -1199;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais déchirer les secrets de votre chair!' WHERE `entry` = -1200;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Purgés par la douleur!' WHERE `entry` = -1201;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous avons faim de vengeance.' WHERE `entry` = -1202;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pas de repos pour les morts en colère.' WHERE `entry` = -1203;
UPDATE `creature_ai_texts` SET `content_loc2` = 'En savoir plus ... Plus les âmes.' WHERE `entry` = -1204;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Relâchez les chiens!' WHERE `entry` = -1205;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Azeroth s\'est recroquevillé trop longtemps sous notre ombre ! Maintenant, sentez le pouvoir de la Croisade Brûlante et le désespoir !' WHERE `entry` = -1206;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre destin est scellé, Azeroth ! Je trouverai les Tessons d\'Aspect et ensuite vous ne vous tiendrez pas debout contre notre puissance !' WHERE `entry` = -1207;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Recroquevillez-vous, petits vers ! Vos héros ne sont rien ! Vos sauveurs seront notre premier festin !' WHERE `entry` = -1208;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Où ? Où sont les Tessons ! Vous ne pouvez pas nous les cacher !' WHERE `entry` = -1209;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre monde mourra,  mortels ! Votre mort est maintenant à portée de  main !' WHERE `entry` = -1210;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Votre propre force me nourrit !' WHERE `entry` = -1211;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ha ! Cet endroit n\'est pas encore digne de mon affliction.' WHERE `entry` = -1212;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous avez aproximativement cinq secondes à vivre.' WHERE `entry` = -1213;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Avec l\'angle et la vitesse précise ...' WHERE `entry` = -1214;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Institut d\'enseignement technique bas calme encore efficace !' WHERE `entry` = -1215;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Une conclusion passée.' WHERE `entry` = -1216;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le traitement se poursuivra un programme!' WHERE `entry` = -1217;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mes calculs ne tiennent pas ...' WHERE `entry` = -1218;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s lève son marteau menaçant ...' WHERE `entry` = -1219;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Aile de ciel ! Je vais vous libérer de votre malédiction sur mon cadavre!' WHERE `entry` = -1220;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous ne quitterez jamais cet endroit... vivant.' WHERE `entry` = -1221;
UPDATE `creature_ai_texts` SET `content_loc2` = 'À moi, mes domestiques !' WHERE `entry` = -1222;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Venez, esprits, accompagnez votre maître !' WHERE `entry` = -1223;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je suis la main du Roi Lich !' WHERE `entry` = -1224;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Aussi... facile !' WHERE `entry` = -1225;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Oh maintenant vous êtes parti et m\'avez mis en colère ! Il est temps de voir la vraie force de la pierre des marées!' WHERE `entry` = -1226;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est la terre sacrée !' WHERE `entry` = -1227;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est la terre sacrée !' WHERE `entry` = -1228;
UPDATE `creature_ai_texts` SET `content_loc2` = 'C\'est la terre sacrée !' WHERE `entry` = -1229;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comment osez vous venir ici ?' WHERE `entry` = -1230;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comment osez vous venir ici ?' WHERE `entry` = -1231;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Comment osez vous venir ici ?' WHERE `entry` = -1232;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les étrangers sont interdits!' WHERE `entry` = -1233;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les étrangers sont interdits!' WHERE `entry` = -1234;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les étrangers sont interdits!' WHERE `entry` = -1235;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Si vous entendez le chuchotement, vous mourez...' WHERE `entry` = -1236;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Bienvenue sur le Vide ...' WHERE `entry` = -1237;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous êtes loin de la maison, étranger.' WHERE `entry` = -1238;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Que les vents inférieurs nous ont-ils apporté ?' WHERE `entry` = -1239;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Arak-ha!' WHERE `entry` = -1240;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Protégez le voile !' WHERE `entry` = -1241;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Feu sombre - venge nous !' WHERE `entry` = -1242;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Ssssekk-sara Rith-nealaak!' WHERE `entry` = -1243;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Dans le nom de Terokk !' WHERE `entry` = -1244;
UPDATE `creature_ai_texts` SET `content_loc2` = '%s commence à convoquer dans un Ligemort Cabal!' WHERE `entry` = -1245;
UPDATE `creature_ai_texts` SET `content_loc2` = '% s commence à convoquer dans un Acolyte Cabal!' WHERE `entry` = -1246;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Invocateur de la Cabale  convoque un Cabale Ligemort à son secours!' WHERE `entry` = -1247;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Invocateur de la Cabale  convoque un Cabale Acolyte à son secours!' WHERE `entry` = -1248;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous êtes un esclave. C\'est tout ce que vous serez jamais.' WHERE `entry` = -1249;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je ne sais pas ce que Blackmoore voit dans vous. Pour mon argent, vous êtes juste un autre sauvage ignorant !' WHERE `entry` = -1250;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Thrall ne sera jamais libre!' WHERE `entry` = -1251;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Croyiez-vous vraiment que vous partiriez d\'ici vivant ?' WHERE `entry` = -1252;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Guardes! Urgh..Guardes..!	' WHERE `entry` = -1253;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous là-bas, chercher de l\'eau rapidement! Eteignez ces flammes avant qu\'elles ne se propagent au reste de la garde! Dépêchez-vous, vous damnation!' WHERE `entry` = -1254;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je sais ce que vous êtes à la hauteur et j\'ai l\'intention d\'y mettre fin, en permanence !' WHERE `entry` = -1255;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pas plus médiocre pour vous.' WHERE `entry` = -1256;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous ne vous mêlerez pas !' WHERE `entry` = -1257;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il est temps de saigner!' WHERE `entry` = -1258;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Exécuter, vous avez fait sauter des poltrons! ' WHERE `entry` = -1259;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Thrall ... ne doit pas  aller...... libre.' WHERE `entry` = -1260;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Assez ! J\'effacerai même votre  existence !' WHERE `entry` = -1261;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous ne pouvez pas lutter contre le destin !' WHERE `entry` = -1262;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous êtes hors de propos....' WHERE `entry` = -1263;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Thrall restera un esclave. Taretha mourra. Vous avez échoué.' WHERE `entry` = -1264;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pas si vite!' WHERE `entry` = -1265;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Luttez autant que vous le souhaitez!' WHERE `entry` = -1266;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Non !... Le maître ne sera pas.... content...' WHERE `entry` = -1267;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Enfin je suis libéré. Cela fait trop longtemps que je n\'ai pas goûté à la vraie liberté !' WHERE `entry` = -1268;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je n\'ai pas d\'égal.' WHERE `entry` = -1269;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Périssez,  mortel.' WHERE `entry` = -1270;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Oui, OUI ! Ahahah !' WHERE `entry` = -1271;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je pense à des vacances. J\'entends dire que le vallon d\'Âtreval est agréable.' WHERE `entry` = -1272;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cesser de temps ne peut pas venir trop tôt.' WHERE `entry` = -1273;
UPDATE `creature_ai_texts` SET `content_loc2` = 'J\'ai entendu dire que Blackmoore a agi étrangement.' WHERE `entry` = -1274;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Cette région est restreinte !' WHERE `entry` = -1275;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Halte!' WHERE `entry` = -1276;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Capitulez immédiatement !' WHERE `entry` = -1277;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Arrêtez-les!' WHERE `entry` = -1278;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Pourquoi ...?' WHERE `entry` = -1279;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Blackmoore aura ... votre tête!' WHERE `entry` = -1280;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je suivais juste... des ordres.' WHERE `entry` = -1281;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Écume maudite !' WHERE `entry` = -1282;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Il est ici, arrêtez-le !' WHERE `entry` = -1283;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Renoncez ou mourez !' WHERE `entry` = -1284;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'irez pas loin ....' WHERE `entry` = -1285;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous croyez que vous avez gagné ?' WHERE `entry` = -1286;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je vais...' WHERE `entry` = -1287;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous n\'avez pas de chance!' WHERE `entry` = -1288;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous avons tout le temps dans le monde ....' WHERE `entry` = -1289;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Tout ce que vous savez... sera défait.' WHERE `entry` = -1290;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous ne pouvez pas nous échapper !' WHERE `entry` = -1291;
UPDATE `creature_ai_texts` SET `content_loc2` = 'HM, affamé.' WHERE `entry` = -1292;
UPDATE `creature_ai_texts` SET `content_loc2` = 'So-ngh-thirsty.' WHERE `entry` = -1293;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Les intrus ont fait une brèche dans le couvoir ! Sonnez l\'alarme ! Protégez les œufs à tout prix !' WHERE `entry` = -1294;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Mortel fou, vous me servez maintenant !' WHERE `entry` = -1295;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Le pouvoir de la lumière est vraiment grand et charitable.' WHERE `entry` = -1296;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Nous serons réunis encore une fois, mon amour...' WHERE `entry` = -1297;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Enfin, il finit...' WHERE `entry` = -1298;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Etranger, trouvez le prince tombé Menethil et mettez fin à son règne de terreur.' WHERE `entry` = -1299;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Devrais-je vivre cela, je me ferai un seule ambition de ma vie à détruire Arthas ...' WHERE `entry` = -1300;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Je ne vais pas le faire ... allez ... continuez sans moi ...' WHERE `entry` = -1301;
UPDATE `creature_ai_texts` SET `content_loc2` = 'La mort me prend ! Je ne peux pas continuer ! Je n\'ai rien...' WHERE `entry` = -1302;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Par la Lumière, vous quitterez ce tombeau !' WHERE `entry` = -581;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous souffrirez éternellement !' WHERE `entry` = -175;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Petite créature faite de chair, votre désir est accordé ! La mort vient pour vous !' WHERE `entry` = -176;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous appartiendrez aux morts honorés.' WHERE `entry` = -818;
UPDATE `creature_ai_texts` SET `content_loc2` = 'Vous paierez pour cette violation.' WHERE `entry` = -821;